name: Docker Image CI

on:
  push:
    paths: 
      - Dockerfile
  pull_request:
    paths: 
      - Dockerfile
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hserr/iirose-bot:dev
    - name: Login Docker account
      run: docker login --username="${{ secrets.USERNAME }}" --password="${{ secrets.PASSWORD }}"
    - name: Push image
      run: docker push hserr/iirose-bot:dev
      
